# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import codeRunner_pb2 as codeRunner__pb2


class codeRunnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.judge = channel.unary_unary(
                '/CodeRunner.codeRunner/judge',
                request_serializer=codeRunner__pb2.codeRunnerRequest.SerializeToString,
                response_deserializer=codeRunner__pb2.codeRunnerRespone.FromString,
                )


class codeRunnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def judge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_codeRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'judge': grpc.unary_unary_rpc_method_handler(
                    servicer.judge,
                    request_deserializer=codeRunner__pb2.codeRunnerRequest.FromString,
                    response_serializer=codeRunner__pb2.codeRunnerRespone.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CodeRunner.codeRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class codeRunner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def judge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CodeRunner.codeRunner/judge',
            codeRunner__pb2.codeRunnerRequest.SerializeToString,
            codeRunner__pb2.codeRunnerRespone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
